// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserLogin.proto

#include "UserLogin.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace skymarlin {
namespace protocol {
namespace auth {
      template <typename>
PROTOBUF_CONSTEXPR UserLoginResult::UserLoginResult(::_pbi::ConstantInitialized) {}
struct UserLoginResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLoginResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLoginResultDefaultTypeInternal() {}
  union {
    UserLoginResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLoginResultDefaultTypeInternal _UserLoginResult_default_instance_;

inline constexpr UserLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        user_pw_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserLogin::UserLogin(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserLoginDefaultTypeInternal() {}
  union {
    UserLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserLoginDefaultTypeInternal _UserLogin_default_instance_;
}  // namespace auth
}  // namespace protocol
}  // namespace skymarlin
static ::_pb::Metadata file_level_metadata_UserLogin_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_UserLogin_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_UserLogin_2eproto = nullptr;
const ::uint32_t TableStruct_UserLogin_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::skymarlin::protocol::auth::UserLogin, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::skymarlin::protocol::auth::UserLogin, _impl_.user_id_),
    PROTOBUF_FIELD_OFFSET(::skymarlin::protocol::auth::UserLogin, _impl_.user_pw_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::skymarlin::protocol::auth::UserLoginResult, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::skymarlin::protocol::auth::UserLogin)},
        {10, -1, -1, sizeof(::skymarlin::protocol::auth::UserLoginResult)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::skymarlin::protocol::auth::_UserLogin_default_instance_._instance,
    &::skymarlin::protocol::auth::_UserLoginResult_default_instance_._instance,
};
const char descriptor_table_protodef_UserLogin_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017UserLogin.proto\022\027skymarlin.protocol.au"
    "th\"-\n\tUserLogin\022\017\n\007user_id\030\001 \001(\t\022\017\n\007user"
    "_pw\030\002 \001(\t\"1\n\017UserLoginResult\"\036\n\006Result\022\024"
    "\n\020EmailNotExisting\020\000b\006proto3"
};
static ::absl::once_flag descriptor_table_UserLogin_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_UserLogin_2eproto = {
    false,
    false,
    148,
    descriptor_table_protodef_UserLogin_2eproto,
    "UserLogin.proto",
    &descriptor_table_UserLogin_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_UserLogin_2eproto::offsets,
    file_level_metadata_UserLogin_2eproto,
    file_level_enum_descriptors_UserLogin_2eproto,
    file_level_service_descriptors_UserLogin_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_UserLogin_2eproto_getter() {
  return &descriptor_table_UserLogin_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_UserLogin_2eproto(&descriptor_table_UserLogin_2eproto);
namespace skymarlin {
namespace protocol {
namespace auth {
const ::google::protobuf::EnumDescriptor* UserLoginResult_Result_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_UserLogin_2eproto);
  return file_level_enum_descriptors_UserLogin_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t UserLoginResult_Result_internal_data_[] = {
    65536u, 0u, };
bool UserLoginResult_Result_IsValid(int value) {
  return 0 <= value && value <= 0;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr UserLoginResult_Result UserLoginResult::EmailNotExisting;
constexpr UserLoginResult_Result UserLoginResult::Result_MIN;
constexpr UserLoginResult_Result UserLoginResult::Result_MAX;
constexpr int UserLoginResult::Result_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class UserLogin::_Internal {
 public:
};

UserLogin::UserLogin(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:skymarlin.protocol.auth.UserLogin)
}
inline PROTOBUF_NDEBUG_INLINE UserLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : user_id_(arena, from.user_id_),
        user_pw_(arena, from.user_pw_),
        _cached_size_{0} {}

UserLogin::UserLogin(
    ::google::protobuf::Arena* arena,
    const UserLogin& from)
    : ::google::protobuf::Message(arena) {
  UserLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:skymarlin.protocol.auth.UserLogin)
}
inline PROTOBUF_NDEBUG_INLINE UserLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_id_(arena),
        user_pw_(arena),
        _cached_size_{0} {}

inline void UserLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserLogin::~UserLogin() {
  // @@protoc_insertion_point(destructor:skymarlin.protocol.auth.UserLogin)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserLogin::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.user_id_.Destroy();
  _impl_.user_pw_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:skymarlin.protocol.auth.UserLogin)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_.ClearToEmpty();
  _impl_.user_pw_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserLogin::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 56, 2> UserLogin::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserLogin_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string user_pw = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UserLogin, _impl_.user_pw_)}},
    // string user_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserLogin, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user_id = 1;
    {PROTOBUF_FIELD_OFFSET(UserLogin, _impl_.user_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string user_pw = 2;
    {PROTOBUF_FIELD_OFFSET(UserLogin, _impl_.user_pw_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\41\7\7\0\0\0\0\0"
    "skymarlin.protocol.auth.UserLogin"
    "user_id"
    "user_pw"
  }},
};

::uint8_t* UserLogin::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:skymarlin.protocol.auth.UserLogin)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string user_id = 1;
  if (!this->_internal_user_id().empty()) {
    const std::string& _s = this->_internal_user_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "skymarlin.protocol.auth.UserLogin.user_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string user_pw = 2;
  if (!this->_internal_user_pw().empty()) {
    const std::string& _s = this->_internal_user_pw();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "skymarlin.protocol.auth.UserLogin.user_pw");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:skymarlin.protocol.auth.UserLogin)
  return target;
}

::size_t UserLogin::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:skymarlin.protocol.auth.UserLogin)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string user_id = 1;
  if (!this->_internal_user_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_user_id());
  }

  // string user_pw = 2;
  if (!this->_internal_user_pw().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_user_pw());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserLogin::_class_data_ = {
    UserLogin::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserLogin::GetClassData() const {
  return &_class_data_;
}

void UserLogin::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserLogin*>(&to_msg);
  auto& from = static_cast<const UserLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:skymarlin.protocol.auth.UserLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (!from._internal_user_pw().empty()) {
    _this->_internal_set_user_pw(from._internal_user_pw());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserLogin::CopyFrom(const UserLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:skymarlin.protocol.auth.UserLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserLogin::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserLogin::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserLogin::InternalSwap(UserLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_id_, &other->_impl_.user_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_pw_, &other->_impl_.user_pw_, arena);
}

::google::protobuf::Metadata UserLogin::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_UserLogin_2eproto_getter, &descriptor_table_UserLogin_2eproto_once,
      file_level_metadata_UserLogin_2eproto[0]);
}
// ===================================================================

class UserLoginResult::_Internal {
 public:
};

UserLoginResult::UserLoginResult(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:skymarlin.protocol.auth.UserLoginResult)
}
UserLoginResult::UserLoginResult(
    ::google::protobuf::Arena* arena,
    const UserLoginResult& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  UserLoginResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:skymarlin.protocol.auth.UserLoginResult)
}









::google::protobuf::Metadata UserLoginResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_UserLogin_2eproto_getter, &descriptor_table_UserLogin_2eproto_once,
      file_level_metadata_UserLogin_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace auth
}  // namespace protocol
}  // namespace skymarlin
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
